# Dependencies
markdown:         redcarpet
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Andy Chen 
  url:            http://ppstay.wordpress.com 
  email:          ppstay@hotmail.com 

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ppstay/ppstay.github.io

highlighter:      pygments
